[kbs-2021kpopawards]
title = "2021 KBS 가요대축제 ─ 네이버TV"
url = "https://tv.naver.com/kbs.2021kpopawards/clips"
entrySelector = "div.cds_area._infiniteCardArea div.cds._MM_CARD"
titleSelector = "dl.cds_info dt.title a tooltip"
linkSelector = "div.cds_type a.cds_thm"
contentSelector = "div.cds_type a.cds_thm span.tm_b"
imageSelector = "div.cds_type a.cds_thm img"
waitUntil = "networkidle"

[sbs-2021sbsgayo]
title = "2021 SBS 가요대전 ─ 네이버TV"
url = "https://tv.naver.com/sbs.2021sbsgayo/clips"
entrySelector = "div.cds_area._infiniteCardArea div.cds._MM_CARD"
titleSelector = "dl.cds_info dt.title a tooltip"
linkSelector = "div.cds_type a.cds_thm"
contentSelector = "div.cds_type a.cds_thm span.tm_b"
imageSelector = "div.cds_type a.cds_thm img"
waitUntil = "networkidle"

[mbc-2021mbctogether]
title = "2021 MBC 가요대제전 ─ 네이버TV"
url = "https://tv.naver.com/mbc.2021mbctogether/clips"
entrySelector = "div.cds_area._infiniteCardArea div.cds._MM_CARD"
titleSelector = "dl.cds_info dt.title a tooltip"
linkSelector = "div.cds_type a.cds_thm"
contentSelector = "div.cds_type a.cds_thm span.tm_b"
imageSelector = "div.cds_type a.cds_thm img"
waitUntil = "networkidle"
